### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by SugarDaddii** [Alex-the-666/Citadel#22]
https://imgur.com/a/3VwsOAh

after i update your citadel mod this was the problem!

**Comment by KKotik** [comment]
[09Feb2021 11:40:30.308] [Render thread/WARN] [net.minecraft.client.Minecraft/]: Failed to load datapacks, can't proceed with server load
java.lang.NullPointerException: null
	at com.github.alexthe666.citadel.config.biome.SpawnBiomeData$SpawnBiomeEntry.matches(SpawnBiomeData.java:84) ~[citadel:1.6.0]
	at com.github.alexthe666.citadel.config.biome.SpawnBiomeData.matches(SpawnBiomeData.java:43) ~[citadel:1.6.0]
	at com.github.alexthe666.alexsmobs.config.BiomeConfig.test(BiomeConfig.java:75) ~[alexsmobs:1.5.1]
	at com.github.alexthe666.alexsmobs.world.AMWorldRegistry.onBiomesLoad(AMWorldRegistry.java:18) ~[alexsmobs:1.5.1]
	at com.github.alexthe666.alexsmobs.AlexsMobs.onBiomeLoadFromJSON(AlexsMobs.java:76) ~[alexsmobs:1.5.1]
	at net.minecraftforge.eventbus.ASMEventHandler_42_AlexsMobs_onBiomeLoadFromJSON_BiomeLoadingEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.common.ForgeHooks.enhanceBiome(ForgeHooks.java:928) ~[forge:?]
	at net.minecraft.world.biome.Biome.lambda$null$8(Biome.java:75) ~[?:?]
	at com.mojang.datafixers.util.Function8.lambda$null$6(Function8.java:22) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.datafixers.util.Function4.lambda$null$2(Function4.java:14) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.serialization.DataResult$Instance.ap2(DataResult.java:315) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.datafixers.kinds.Applicative.ap4(Applicative.java:84) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.serialization.codecs.RecordCodecBuilder$Instance$7.decode(RecordCodecBuilder.java:404) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.serialization.codecs.RecordCodecBuilder$2.decode(RecordCodecBuilder.java:107) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.serialization.MapDecoder.lambda$compressedDecode$0(MapDecoder.java:52) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.serialization.DataResult.lambda$flatMap$10(DataResult.java:138) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.serialization.DataResult.flatMap(DataResult.java:136) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.serialization.MapDecoder.compressedDecode(MapDecoder.java:52) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.serialization.MapCodec$MapCodecCodec.decode(MapCodec.java:91) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.serialization.Decoder.parse(Decoder.java:18) ~[datafixerupper-4.0.26.jar:?]
	at net.minecraft.util.registry.WorldSettingsImport$IResourceAccess$1.func_241879_a(WorldSettingsImport.java:194) ~[?:?]
	at net.minecraft.util.registry.WorldSettingsImport.func_241805_a_(WorldSettingsImport.java:131) ~[?:?]
	at net.minecraft.util.registry.WorldSettingsImport.lambda$decode$5(WorldSettingsImport.java:105) ~[?:?]
	at com.mojang.serialization.DataResult.lambda$flatMap$10(DataResult.java:138) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.serialization.DataResult.flatMap(DataResult.java:136) ~[datafixerupper-4.0.26.jar:?]
	at net.minecraft.util.registry.WorldSettingsImport.func_241797_a_(WorldSettingsImport.java:104) ~[?:?]
	at net.minecraft.util.registry.DynamicRegistries.func_243610_a(DynamicRegistries.java:144) ~[?:?]
	at net.minecraft.util.registry.DynamicRegistries.func_243608_a(DynamicRegistries.java:132) ~[?:?]
	at net.minecraft.util.registry.WorldSettingsImport.func_244336_a(WorldSettingsImport.java:53) ~[?:?]
	at net.minecraft.util.registry.WorldSettingsImport.func_244335_a(WorldSettingsImport.java:48) ~[?:?]
	at net.minecraft.client.Minecraft.lambda$createWorld$24(Minecraft.java:1689) ~[?:?]
	at net.minecraft.client.Minecraft.func_238189_a_(Minecraft.java:1865) ~[?:?]
	at net.minecraft.client.Minecraft.loadWorld(Minecraft.java:1712) ~[?:?]
	at net.minecraft.client.Minecraft.func_238192_a_(Minecraft.java:1685) ~[?:?]
	at net.minecraft.client.gui.screen.CreateWorldScreen.redirect$bhi000$redirectOnCreateLevel(CreateWorldScreen.java:721) ~[?:?]
	at net.minecraft.client.gui.screen.CreateWorldScreen.func_195352_j(CreateWorldScreen.java:260) ~[?:?]
	at net.minecraft.client.gui.screen.CreateWorldScreen.lambda$init$11(CreateWorldScreen.java:205) ~[?:?]
	at net.minecraft.client.gui.widget.button.Button.func_230930_b_(SourceFile:33) ~[?:?]
	at net.minecraft.client.gui.widget.button.AbstractButton.func_230982_a_(SourceFile:16) ~[?:?]
	at net.minecraft.client.gui.widget.Widget.func_231044_a_(Widget.java:136) ~[?:?]
	at net.minecraft.client.gui.INestedGuiEventHandler.func_231044_a_(SourceFile:27) ~[?:?]
	at net.minecraft.client.MouseHelper.lambda$mouseButtonCallback$0(MouseHelper.java:87) ~[?:?]
	at net.minecraft.client.gui.screen.Screen.func_231153_a_(Screen.java:427) ~[?:?]
	at net.minecraft.client.MouseHelper.func_198023_a(MouseHelper.java:85) ~[?:?]
	at net.minecraft.client.MouseHelper.lambda$null$4(MouseHelper.java:175) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.execute(ThreadTaskExecutor.java:104) ~[?:?]
	at net.minecraft.client.MouseHelper.lambda$registerCallbacks$5(MouseHelper.java:174) ~[?:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) ~[lwjgl-glfw-3.2.2.jar:build 10]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10]
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174) ~[lwjgl-glfw-3.2.2.jar:build 10]
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(SourceFile:127) ~[?:?]
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:999) ~[?:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?]
	at net.minecraft.client.main.Main.main(Main.java:184) ~[minecraft-1.16.5-client.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_271]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_271]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_271]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_271]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.5-36.0.15-launcher.jar:36.0]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?]
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:50) [ForgeWrapper-1.4.2.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_271]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_271]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_271]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_271]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]

**Comment by AdnanuReeves** [comment]
Having same issue

**Comment by RustBandit** [comment]
anyone figure it out?

**Comment by pibblepower** [comment]
I'm having the same issue.

**Comment by AdnanuReeves** [comment]
Has this been fixed yet?
