### ISSUE TITLE
Constantly makes my server crash.

### ISSUE THREAD

**Issue by surister** [Alex-the-666/Citadel#4]
Hi, I'm running a modpack with 140+ mods, Citadel included.

Every time Citadel starts the version check, most of the time, connection cannot be made, iddles there until an exception is thrown making the server start stop.

` 
---- Minecraft Crash Report ----
  2 // Why is it breaking :(
  3 
  4 Time: 3/18/20 8:28 AM
  5 Description: Exception in server tick loop
  6 
  7 net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
  8         Citadel (citadel) encountered an error during the common_setup event phase
  9 §7null
 10 ]
 11         at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:201) ~[?:?] {re:classloading}
 12         at net.minecraftforge.fml.ModLoader.loadMods(ModLoader.java:154) ~[?:?] {re:classloading}
 13         at net.minecraftforge.fml.server.ServerModLoader.begin(ServerModLoader.java:46) ~[?:?] {re:classloading}
 14         at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:121) ~[?:?] {re:classloading,pl:accesstransformer:B}
 15         at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:598) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
 16         at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242] {}
`

Is there any way to disable this check?

**Comment by surister** [comment]
`[08:39:21] [Forge Version Check/INFO] [ne.mi.fm.VersionChecker/]: [citadel] Starting version check at http://myurl.me/`

Always stuck here
