### ISSUE TITLE
Console error spam NPE

### ISSUE THREAD

**Issue by amoooooo** [Alex-the-666/Citadel#42]
I get TON of console error spam from Citadel, all of it is a NPE at com.github.alexthe666.citadel.server.entity.datatracker.EntityProperties.getEntity
and com.github.alexthe666.iceandfire.entity.props.ChainEntityProperties.loadNBTData(

full error: https://hastebin.com/uhujurekoc.apache

**Comment by laneyfamily** [comment]
Getting the exact same thing, each time it seems to correspond with a lag spike as well

**Comment by Elec0** [comment]
I'm also getting it.

https://pastebin.com/UVhyZVeN

**Comment by Darkmega18** [comment]
*raises hand* also, I also think I have a crash in relation to it too when it interacts with villagers being customized by Custom villager trades mod, cause theres just a lot of the nulls firing in the latest.log just before they happen, with large amounts of lag happening also.

**Comment by Graftax** [comment]
I am also getting what appears to be the same log spam.
I cannot paste my whole log as its too big, but the following error is repeated hundreds of times. If asked I can try to host the log somewhere else.

`[26Jul2021 13:41:03.711] [Render thread/FATAL] [net.minecraft.util.concurrent.ThreadTaskExecutor/]: Error executing task on Client
java.lang.NullPointerException: null
	at com.github.alexthe666.citadel.server.entity.datatracker.EntityProperties.getEntity(EntityProperties.java:63) ~[citadel:1.7.2-1.16.5]
	at com.github.alexthe666.iceandfire.entity.props.ChainEntityProperties.loadNBTData(ChainEntityProperties.java:54) ~[iceandfire:2.1.8-1.16.5]
	at com.github.alexthe666.citadel.server.entity.datatracker.EntityProperties.loadTrackingSensitiveData(EntityProperties.java:112) ~[citadel:1.7.2-1.16.5]
	at com.github.alexthe666.citadel.ClientProxy.handlePropertiesPacket(ClientProxy.java:126) ~[citadel:1.7.2-1.16.5]
	at com.github.alexthe666.citadel.server.message.PropertiesMessage$Handler.lambda$handle$0(PropertiesMessage.java:50) ~[citadel:1.7.2-1.16.5]
	at net.minecraftforge.fml.network.NetworkEvent$Context.enqueueWork(NetworkEvent.java:215) ~[forge:?]
	at com.github.alexthe666.citadel.server.message.PropertiesMessage$Handler.handle(PropertiesMessage.java:48) ~[citadel:1.7.2-1.16.5]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.lambda$tryDecode$3(IndexedMessageCodec.java:128) ~[forge:?]
	at java.util.Optional.ifPresent(Unknown Source) ~[?:1.8.0_291]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.tryDecode(IndexedMessageCodec.java:128) ~[forge:?]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.consume(IndexedMessageCodec.java:162) ~[forge:?]
	at net.minecraftforge.fml.network.simple.SimpleChannel.networkEventListener(SimpleChannel.java:80) ~[forge:?]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.fml.network.NetworkInstance.dispatch(NetworkInstance.java:86) ~[forge:?]
	at net.minecraftforge.fml.network.NetworkHooks.lambda$onCustomPayload$1(NetworkHooks.java:91) ~[forge:?]
	at java.util.Optional.map(Unknown Source) ~[?:1.8.0_291]
	at net.minecraftforge.fml.network.NetworkHooks.onCustomPayload(NetworkHooks.java:91) ~[forge:?]
	at net.minecraft.client.network.play.ClientPlayNetHandler.func_147240_a(ClientPlayNetHandler.java:1904) ~[?:?]
	at net.minecraft.network.play.server.SCustomPayloadPlayPacket.func_148833_a(SCustomPayloadPlayPacket.java:59) ~[?:?]
	at net.minecraft.network.play.server.SCustomPayloadPlayPacket.func_148833_a(SCustomPayloadPlayPacket.java:11) ~[?:?]
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103) ~[?:?]
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:947) ~[?:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?]
	at net.minecraft.client.main.Main.main(Main.java:184) ~[minecraft.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_291]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_291]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_291]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_291]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.5-36.1.61.jar:36.1]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?]`

**Comment by Darkmega18** [comment]
Everyone. there is a setting in the config for citadel. literally one of two in there. turn off the one related to tracking data for entities and the log spam goes away. although it does have mention of some special things that might break with other Alex mods. but it's better than being spammed and lagged by the spam and seeing nothing else.

**Comment by TLATER** [comment]
This looks like a duplicate of #40

**Comment by TLATER** [comment]
I can also confirm that a downgrade, [as suggested](https://github.com/Alex-the-666/Citadel/issues/40#issuecomment-886711619), fixes the log spam for me. This vaguely makes sense given the changelog.

Whether this results in more memory thrashing than disabling the setting, I'm not sure.

**Comment by TheWitherlord** [comment]
Getting the same error also, the datatracker is a little funky when Ice and Fire is installed.

**Comment by aneuhold** [comment]
> Everyone. there is a setting in the config for citadel. literally one of two in there. turn off the one related to tracking data for entities and the log spam goes away. although it does have mention of some special things that might break with other Alex mods. but it's better than being spammed and lagged by the spam and seeing nothing else. While we wait for a reply atleast.

This was the answer personally. Thank you!
